print ("Numbers and Operations")
a = 10
b = 70
print ("a =", a)
print ("b =", b)
print ("a + b =",a + b, "a - b =",a - b, "a * b =",a * b, "a / b =",a / b, "a // b =",a // b)
print ("hello" * 2)
print ("a % b =", a % b)
print ("a ** b =",a ** b)
a = 60
b = 30
print ("a ** b =",a ** b)
print ("a // b =", a // b)
print (f"a  ** b = {a ** b}")
print (f"a // b = {a // b}")

x =int (input ("enter first number:"))
y= int (input ("enter second number:"))
print (f"addition: {x + y}")
print (f"x+y={x+y}")
print (f"floor division: {x // y}")
print (f"exponentiation: {x ** y}")
print (f"modulu: {x % y}")
print (f"x + y = {x + y}")
print (f"addition: {x + y}")
print ("x - y =",x - y)
print ("substraction:",x - y)
print (f"x * y= {x * y}")
print (f"multiplication: {x * y}")
print (f"x / y= {x / y}")
print (f"division: {x / y}")
print ("x // y=",x // y)
print ("floor division:",x // y)
print (f"modulu: {x % y}")
print (f"x % y=", x % y)
print (f"x**y = {x**y}")
print (f"exponentiation: {x ** y}")